[tox]
isolated_build =
    True

envlist =
    pypy
    py39
    py310
    py311
    py312
    py313
    py314
    py315

[testenv]
deps =
    -r requirements.txt
    parameterized==0.9.0
    pytest==8.4.2
usedevelop =
    true
commands =
    pytest -q {posargs}

[testenv:coverage]
deps =
    -r requirements.txt
    parameterized==0.9.0
    pytest==8.4.2
    coverage==7.13.2
    pytest-cov==7.0.0
basepython =
    python3
setenv =
    PYTHONPATH = src
commands =
    pytest -q --cov=src/mediapills --cov-report term --cov-fail-under=80 {posargs}

[testenv:linter]
deps =
    flake8==7.3.0
skip_install =
    true
basepython =
    python3
commands =
    flake8 --max-line-length=90

[testenv:mypy]
deps =
    mypy==1.19.1
skip_install =
    true
basepython =
    python3
commands =
    mypy ./src --ignore-missing-imports --strict

[testenv:pre-commit]
deps =
    pre-commit==3.5.0
skip_install =
    true
basepython =
    python3
commands =
    pre-commit run --all-files --show-diff-on-failure

[testenv:build]
deps =
    build==0.7.0
    twine==3.4.2
commands =
	python -m build --wheel
;    twine check dist/*
